version: "3.7"

services:
  tourneys-bot-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: tourneys-bot-docker
    command: npm run start
